config/routes.rb
PlanteAr::Application.routes.draw do
  resources :clients

  resources :payment_types

  resources :sells

  resources :line_items

  resources :purchases

  resources :products

  resources :providers

  get "home/index"
  get "products/gallery"

  root :to => 'home#index'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base

  include ActiveModel::Dirty

  attr_accessible :amount, :discount, :product_id, :unit_price, :subtotal, :line_item_product_sell_price, :line_item_product_name
  attr_accessible :product_attributes
  # attr_accessible :_destroy
  # attr_accessor :_destroy
  belongs_to :line_itemable, :polymorphic => true

  # belongs_to :purchase
  belongs_to :product

  accepts_nested_attributes_for :product, :reject_if => lambda { |a| a[:product_id].blank? && a[:line_item_product_name].blank? }, :allow_destroy => true
  
  validates_presence_of :amount, :message => "La cantidad no puede estar en blanco"
  validates_numericality_of :amount, :greater_than => 0, :unless => lambda { self.amount.blank? },:message => "La cantidad no puede ser Negativa"

  validates_presence_of :unit_price, :message => "El precio unitario no puede estar en blanco"
  validates_numericality_of :unit_price, :greater_than => 0, :unless => lambda { self.unit_price.blank? }, :message => "El precio unitario no puede ser Negativo"
  
  validates_presence_of :subtotal, :message => "El subtotal no puede estar en blanco"
  validates_numericality_of :subtotal, :greater_than => 0,:unless => lambda { self.subtotal.blank? }, :message => "El subtotal no puede ser negativo"

  def line_item_product_sell_price
    product.sell_price if product.present?
  end

  def line_item_product_name
    product.name if product.present?
  end
  

  def line_item_product_sell_price= value
    if (Product.exists?(product_id))
      product = Product.find(product_id)
      product.sell_price = value
      product.save!
    end
  end

  def line_item_product_name= value
    if (Product.find_by_name(value) == nil && value != "")
      product = Product.new()
      product.name = value
      product.save!
      self.product_id = product.id
      self.save
    elsif (Product.find_by_name(value) != nil)
      product = Product.find_by_name(value)
      self.product_id = product.id
      self.save
    end
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.json
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @line_item = LineItem.new(params[:line_item])
    respond_to do |format|
      if @line_item.save
        
        format.html { redirect_to @line_item, notice: 'Line item was successfully created.' }
        format.json { render json: @line_item, status: :created, location: @line_item }
      else
        format.html { render action: "new" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def update
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="alert alert-error">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :unit_price %>
    <%= f.text_field :unit_price %>
  </div>
  <div class="field">
    <%= f.label :discount %>
    <%= f.text_field :discount %>
  </div>
  <div class="actions">
    <%= f.submit, :class=>"btn" %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Amount</th>
    <th>Unit price</th>
    <th>Discount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @line_items.each do |line_item| %>
  <tr>
    <td><%= line_item.product_id %></td>
    <td><%= line_item.amount %></td>
    <td><%= line_item.unit_price %></td>
    <td><%= line_item.discount %></td>
    <td><%= link_to 'Show', line_item %></td>
    <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
    <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>



<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<% if !notice.nil? %>
  <div class="alert alert-success"><%= notice %></div>
<% end%>

<p>
  <b>Producto:</b>
  <%= @line_item.product_id %>
</p>

<p>
  <b>Cantidad:</b>
  <%= @line_item.amount %>
</p>

<p>
  <b>Precio unitario:</b>
  <%= @line_item.unit_price %>
</p>

<p>
  <b>Descuento:</b>
  <%= @line_item.discount %>
</p>


<%= link_to 'Editar', edit_line_item_path(@line_item) %> |
<%= link_to 'Volver', line_items_path %>