config/routes.rb
PlanteAr::Application.routes.draw do
  resources :clients

  resources :payment_types

  resources :sells

  resources :line_items

  resources :purchases

  resources :products

  resources :providers

  get "home/index"
  get "products/gallery"

  root :to => 'home#index'

end

app/models/sell.rb
class Sell < ActiveRecord::Base
  attr_accessible :amount, :date, :payment_type_id, :discount
  attr_accessible :line_items_attributes
  attr_accessible :payment_type_attributes
  attr_accessible :products_attributes
  
  
  has_many :line_items, :as => :line_itemable
  has_many :products, :through => :line_items
  
  has_one :payment_type

  accepts_nested_attributes_for :line_items, :reject_if => lambda { |a| a[:product_id].blank? && a[:line_item_product_name].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :payment_type

  validates_presence_of :date, :message=>"La fecha no puede estar en blanco"
  validates_presence_of :line_items, :message=>"Al menos debe completar una linea de venta"
  validates_presence_of :payment_type_id, :message=>"Debe seleccion un metodo de pago"


  def update_products(action)
    if(action == "Insert")
        line_items.each do |line| 
          @product = Product.find(line.product_id)
          @product.sell_price = line.unit_price
          @product.stock = @product.stock.to_i - line.amount unless @product.stock.to_i == 0
          @product.save
        end
    elsif (action == "Update")
        line_items.each do |line|
          if (line.previous_changes[:product_id].nil?)
              @product = Product.find(line.product_id)
              @product.sell_price = line.previous_changes[:unit_price][1] unless line.previous_changes[:unit_price].nil?
              @product.stock = @product.stock.to_i + line.previous_changes[:amount][0] - line.previous_changes[:amount][1] unless (line.previous_changes[:amount].nil?) 
              @product.save
            elsif (line.previous_changes[:product_id][0] == nil)
              @product = Product.find(line.product_id)
              @product.sell_price = line.unit_price
              @product.stock = @product.stock.to_i - line.amount
              @product.save
          end
        end
    end
end
end

app/controllers/sells_controller.rb
class SellsController < ApplicationController
  # GET /sells
  # GET /sells.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json do 
        render json: SellsDatatable.new(view_context)
      end
    end
  end

  # GET /sells/1
  # GET /sells/1.json
  def show
    @sell = Sell.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sell }
    end
  end

  # GET /sells/new
  # GET /sells/new.json
  def new
    @sell = Sell.new
    3.times do
      @sell.line_items.build
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sell }
    end
  end

  # GET /sells/1/edit
  def edit
    @sell = Sell.find(params[:id])
    @sell.line_items.build

  end

  # POST /sells
  # POST /sells.json
  def create
    @sell = Sell.new(params[:sell])
    respond_to do |format|
      if @sell.save
        @sell.update_products("Insert")
        format.html { redirect_to @sell, notice: 'Venta registrada exitosamente!' }
        format.json { render json: @sell, status: :created, location: @sell }
      else
         3.times do
          @sell.line_items.build
        end
        format.html { render action: "new" }
        format.json { render json: @sell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sells/1
  # PUT /sells/1.json
  def update
    @sell = Sell.find(params[:id])

    respond_to do |format|
      if @sell.update_attributes(params[:sell])
        @sell.update_products("Update")
        format.html { redirect_to @sell, notice: 'Sell was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sells/1
  # DELETE /sells/1.json
  def destroy
    @sell = Sell.find(params[:id])
    @sell.destroy

    respond_to do |format|
      format.html { redirect_to sells_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sells_helper.rb
module SellsHelper
end

app/views/sells/_form.html.erb
<%= form_for(@sell) do |f| %>
  <% if @sell.errors.any? %>
    <div class="alert alert-error">
      <h2><%= pluralize(@sell.errors.count, "fucking error") %></h2>
      <ul>
      <% @sell.errors.values.each do |msg| %>
        <li><%= msg[0] %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table class="table">
    <thead>
    <tr>
      <th colspan="3">
        <%= f.select :payment_type_id, PaymentType.all.collect {|p| [ p.name, p.id ] }, {:prompt => 'Seleccione Metodo de pago'},{:class=>"input-large"} %>
      </th>
      <th colspan="3">
        <div>
        <%= f.date_select :date, {:use_month_names => month_names }, {:class=>"input-small pull-right"} %>
        </div>
      </th>
    </tr>
    </thead>
    <tfoot>
    <tr>
      <td colspan="4">
        <h2 class="pull-right">Total $</h2>
      </td>
      <td colspan="1" class="input-prepend">
      <span class="add-on">%</span>
      <%= f.text_field :discount, :placeholder=>"Descuento", :id=>"total_discount", :class=>"prependedInput input-mini" %>
      </td>
      <td colspan="1">
      <%= f.text_field :amount, :placeholder=>"Total", :id=>"total_amount", :class=>"input-mini pull-right" %>
      </td>
    </tr>
    <tr>
      <td colspan="6">
        <%= link_to_add_fields "Agregar lineas de venta..", f, :line_items %>
        <%= f.submit "Registrar venta", :class=>"btn btn-success pull-right" %>
        <%= link_to 'Cancelar', purchases_path, {:class=>"btn btn-danger pull-right"} %>
      </td>
    </tr>
    </tfoot>
    <tbody>
    <%= f.fields_for :line_items do | builder | %>
      <%= render "line_item_fields", :f => builder %>
    <% end %>
    </tbody>
<% end %>

app/views/sells/_line_item_fields.html.erb
<tr  class="line_fields">
  <td>
  	<%= f.select :product_id, Product.all.collect {|p| [ p.name, p.id ] }, {:include_blank => true}, {:class=>"product-field input-xxlarge"}%>
  </td>
  <td class="new_product_field">
    <%= f.text_field :line_item_product_name, :placeholder=>"Nombre", :class=>"input-xxlarge" %>
  </td>
  <td>
    Nuevo? <input type="checkbox"></input>
  </td>
  <td class="input-prepend">
    <span class="add-on">#</span>
    <%= f.number_field :amount, :placeholder=>"Cantidad", :title=>"Cantidad", :class=>"prependedInput amount-field input-mini pull-right" %>
  </td>
  <td class="input-prepend">
    <span class="add-on">$</span>
    <%= f.text_field :unit_price, :placeholder=>"Precio", :title=>"Precio", :class=>"prependedInput price-field input-mini pull-right" %>
  </td>
  <td class="input-prepend">
      <span class="add-on">%</span>
      <%= f.text_field :discount, :placeholder=>"Descuento", :title=>"Descuento", :class=>"prependedInput discount-field input-mini" %>
    </td>
  <td><%= f.text_field :subtotal, :placeholder=>"SubTotal", :title=>"SubTotal" , :class=>"subtotal-field input-mini pull-right" %>
  	<%= f.hidden_field :_destroy %>
   	<%= link_to "Borrar", "#", :class=>"remove_fields" %>
  </td>
</tr>

app/views/sells/edit.html.erb
<h1>Editar Venta</h1>

<%= form_for(@sell) do |f| %>
  <% if @sell.errors.any? %>
    <div class="alert alert-error">
      <h2><%= pluralize(@sell.errors.count, "error") %> ha impedido que este formulario sea guardado:</h2>
      <ul>
      <% @sell.errors.values.each do |msg| %>
        <li><%= msg[0] %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table">
    <thead>
    <tr>
      <th colspan="3">
          <div>
            <%= f.select :payment_type_id, PaymentType.all.collect {|p| [ p.name, p.id ] }, {:prompt => 'Seleccione Metodo de pago'},{:class=>"input-large"} %>
          </div>
      </th>
      <th colspan="3">
        <div>
        <%= f.date_select :date, {:use_month_names => month_names}, {:class=>"input-small pull-right"} %>
        </div>
      </th>
    </tr>
    </thead>
    <tfoot>
    <tr>
      <td colspan="4">
        <h2 class="pull-right">Total $</h2>
      </td>
      <td colspan="1" class="input-prepend">
      <span class="add-on">%</span>
      <%= f.text_field :discount, :placeholder=>"Descuento", :id=>"total_discount", :class=>"prependedInput input-mini" %>
      </td>
      <td colspan="1">
      <%= f.text_field :amount, :placeholder=>"Total", :id=>"total_amount", :class=>"input-mini pull-right" %>
      </td>
    </tr>
    <tr>
      <td colspan="6">
        <%= link_to_add_fields "Agregar lineas de venta..", f, :line_items %>
        <%= f.submit "Actualizar venta", :class=>"btn btn-success pull-right" %>
        <%= link_to 'Cancelar', sells_path, {:class=>"btn btn-danger pull-right"} %>
      </td>
    </tr>
    </tfoot>
    <tbody>
    <%= f.fields_for :line_items do | builder | %>
      <%= render "line_item_fields", :f => builder %>
    <% end %>
    </tbody>
<% end %>

app/views/sells/index.html.erb
<h1>Ventas</h1>
<h3>Mostrando: <small>Todas</small></h3> 
<div class='form-inline'>
<a id="sells-today">Solo hoy</a> || 
<a id="sells-yesterday">Solo ayer</a> || 
	<%= label :day, "Dia" %>
	<%= text_field :day, {}, {:id => "date_day", :placeholder => "Dia",:class => 'input-mini'} %>
	<%= label :month, "Mes" %>
	<%= select_month(Date.today,{:use_month_names => month_names},:class => 'input-medium') %>
	<%= label :year, "Año" %>
	<%= select_year(Date.today,{},:class => 'input-mini') %>
	<a id="custom-filter" class="btn btn-success">Filtrar</a> ||
<a id="sells-remove"> Remover filtros</a> 
</div>
<br></br>
<table id="sells"class="table table-striped table-bordered" data-source="<%= sells_url(format: "json") %>">
 <thead>
  <tr>
      <th>Medio de pago</th>
      <th>Monto</th>
      <th>Fecha</th>
    <th></th>
  </tr>
 </thead>
 <tbody>
  </tbody>

</table>

<br></br>

<%= link_to 'Nueva Venta', new_sell_path, :class=>"btn btn-success" %>

app/views/sells/new.html.erb
<h1>Nueva Venta</h1>

<%= render 'form' %>

app/views/sells/show.html.erb
<% if !notice.nil? %>
  <div class="alert alert-success"><%= notice %></div>
<% end%>

<h1>Resumen de Venta</h1>

<%= form_for(@sell) do |f| %>
  <table class="table">
    <thead>
    <tr>
      <th colspan="4">
          <div>
          	<input type="text" disabled="true" class="input-large text-center"value='<%= PaymentType.find(@sell.payment_type_id).name %>'></input>
          </div>
      </th>
      <th colspan="2">
        <div>
        <input type="text" disabled="true" class="input-small pull-right"value='<%= @sell.date %>'></input>
        </div>
      </th>
    </tr>
    </thead>
    <tfoot>
    <tr>
    	<td colspan="1">
    		<%= link_to "Editar", edit_sell_path(@sell) %>
    	</td>	
      <td colspan="3">
        <h2 class="pull-right">Total $</h2>
      </td>
      <td colspan="1" class="input-prepend">
      <span class="add-on">%</span>
        <input type="text" disabled="true" class="input-small pull-right"value='<%= @sell.discount %>'></input>
      </td>
      <td colspan="1">
        <input type="text" disabled="true" class="input-small pull-right"value='<%= @sell.amount %>'></input>
      </td>
    </tr>
    </tfoot>
    <tbody>
    	<% @sell.line_items.each do | line | %>
    		<tr  class="line_fields">
  				<td colspan="2">
  					<input type="text" disabled="true" class="input-xxlarge"value='<%= Product.find(line.product_id).name %>'></input>
  				</td>
  				<td>
  					<input type="text" disabled="true" class="input-mini pull-right"value='<%= line.amount %>'></input>
		  		</td>
		  		<td>
		  			<input type="text" disabled="true" class="input-mini pull-right"value='<%= line.unit_price %>'></input>
		  		</td>
		  		<td class="input-prepend">
		      		<span class="add-on">%</span>
		      		<input type="text" disabled="true" class="input-mini"value='<%= line.discount %>'></input>
		    	</td>
		  		<td><input type="text" disabled="true" class="input-mini pull-right"value='<%= line.subtotal %>'></input>
		  		</td>
			</tr>
    	<% end %>
    </tbody>
<% end %>