config/routes.rb
PlanteAr::Application.routes.draw do
  resources :clients

  resources :payment_types

  resources :sells

  resources :line_items

  resources :purchases

  resources :products

  resources :providers

  get "home/index"
  get "products/gallery"

  root :to => 'home#index'

end

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav" id="nav">
	<li>
		<%= link_to "Proveedores", providers_path %>
	</li>
	<li class="dropdown">
		<a class="dropdown-toggle" data-toggle="dropdown" href="#">Productos
			<b class="carret"></b>
		</a>
		<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
			<li>
				<%= link_to "Admin", products_path %>
			</li>
			<li>
				<%= link_to "Galeria", root_path %>
			</li>	
		</ul>
	</li>
	<li>
		<%= link_to "Compras", purchases_path %>
	</li>
	<li>
		<%= link_to "Registrar compra", new_purchase_path %>
	</li>
	<li>
		<%= link_to "Ventas", sells_path %>
	</li>
	<li>
		<%= link_to "Registrar venta", new_sell_path %>
	</li>
	<li>
		<%= link_to "Clientes", clients_path %>
	</li>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myapp" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag  :application %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller.controller_name %>" data-spy="scroll" data-target="#nav">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->    
    <script type="text/javascript"></script>
  </body>
</html>